//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PruebaTecnicaNetModel", "FK_States_Country_Id", "Countries", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PruebaDesarrolladorNet.DataAccess.Countries), "States", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PruebaDesarrolladorNet.DataAccess.States))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PruebaTecnicaNetModel", "FK_Towns_State_Id", "States", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PruebaDesarrolladorNet.DataAccess.States), "Towns", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PruebaDesarrolladorNet.DataAccess.Towns))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PruebaTecnicaNetModel", "FK_WeatherReports_Towns_ID", "Towns", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PruebaDesarrolladorNet.DataAccess.Towns), "WeatherReports", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PruebaDesarrolladorNet.DataAccess.WeatherReports))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PruebaTecnicaNetModel", "FK_WeatherReports_User_Id", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PruebaDesarrolladorNet.DataAccess.Users), "WeatherReports", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PruebaDesarrolladorNet.DataAccess.WeatherReports))]

// Nombre de archivo original:
// Fecha de generación: 25/04/2021 20:45:47
namespace PruebaDesarrolladorNet.DataAccess
{
    
    /// <summary>
    /// No hay ningún comentario para PruebaTecnicaNetModel.Countries en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// country_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PruebaTecnicaNetModel", Name="Countries")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Countries : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Countries.
        /// </summary>
        /// <param name="country_id">Valor inicial de country_id.</param>
        /// <param name="name">Valor inicial de name.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Countries CreateCountries(int country_id, string name)
        {
            Countries countries = new Countries();
            countries.country_id = country_id;
            countries.name = name;
            return countries;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad country_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int country_id
        {
            get
            {
                return this._country_id;
            }
            set
            {
                this.Oncountry_idChanging(value);
                this.ReportPropertyChanging("country_id");
                this._country_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("country_id");
                this.Oncountry_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _country_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncountry_idChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncountry_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad code en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string code
        {
            get
            {
                return this._code;
            }
            set
            {
                this.OncodeChanging(value);
                this.ReportPropertyChanging("code");
                this._code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("code");
                this.OncodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _code;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncodeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncodeChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad name en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad active en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<short> active
        {
            get
            {
                return this._active;
            }
            set
            {
                this.OnactiveChanging(value);
                this.ReportPropertyChanging("active");
                this._active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("active");
                this.OnactiveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<short> _active;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanging(global::System.Nullable<short> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanged();
        /// <summary>
        /// No hay ningún comentario para States en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PruebaTecnicaNetModel", "FK_States_Country_Id", "States")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<States> States
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<States>("PruebaTecnicaNetModel.FK_States_Country_Id", "States");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<States>("PruebaTecnicaNetModel.FK_States_Country_Id", "States", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para PruebaTecnicaNetModel.States en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// state_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PruebaTecnicaNetModel", Name="States")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class States : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto States.
        /// </summary>
        /// <param name="state_id">Valor inicial de state_id.</param>
        /// <param name="name">Valor inicial de name.</param>
        /// <param name="active">Valor inicial de active.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static States CreateStates(int state_id, string name, short active)
        {
            States states = new States();
            states.state_id = state_id;
            states.name = name;
            states.active = active;
            return states;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad state_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int state_id
        {
            get
            {
                return this._state_id;
            }
            set
            {
                this.Onstate_idChanging(value);
                this.ReportPropertyChanging("state_id");
                this._state_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("state_id");
                this.Onstate_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _state_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onstate_idChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onstate_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad code en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string code
        {
            get
            {
                return this._code;
            }
            set
            {
                this.OncodeChanging(value);
                this.ReportPropertyChanging("code");
                this._code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("code");
                this.OncodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _code;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncodeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncodeChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad name en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad active en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short active
        {
            get
            {
                return this._active;
            }
            set
            {
                this.OnactiveChanging(value);
                this.ReportPropertyChanging("active");
                this._active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("active");
                this.OnactiveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _active;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanged();
        /// <summary>
        /// No hay ningún comentario para Countries en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PruebaTecnicaNetModel", "FK_States_Country_Id", "Countries")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Countries Countries
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Countries>("PruebaTecnicaNetModel.FK_States_Country_Id", "Countries").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Countries>("PruebaTecnicaNetModel.FK_States_Country_Id", "Countries").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Countries en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Countries> CountriesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Countries>("PruebaTecnicaNetModel.FK_States_Country_Id", "Countries");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Countries>("PruebaTecnicaNetModel.FK_States_Country_Id", "Countries", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para Towns en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PruebaTecnicaNetModel", "FK_Towns_State_Id", "Towns")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Towns> Towns
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Towns>("PruebaTecnicaNetModel.FK_Towns_State_Id", "Towns");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Towns>("PruebaTecnicaNetModel.FK_Towns_State_Id", "Towns", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para PruebaTecnicaNetModel.Towns en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// town_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PruebaTecnicaNetModel", Name="Towns")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Towns : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Towns.
        /// </summary>
        /// <param name="town_id">Valor inicial de town_id.</param>
        /// <param name="name">Valor inicial de name.</param>
        /// <param name="code">Valor inicial de code.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Towns CreateTowns(int town_id, string name, string code)
        {
            Towns towns = new Towns();
            towns.town_id = town_id;
            towns.name = name;
            towns.code = code;
            return towns;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad town_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int town_id
        {
            get
            {
                return this._town_id;
            }
            set
            {
                this.Ontown_idChanging(value);
                this.ReportPropertyChanging("town_id");
                this._town_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("town_id");
                this.Ontown_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _town_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ontown_idChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ontown_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad name en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad code en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string code
        {
            get
            {
                return this._code;
            }
            set
            {
                this.OncodeChanging(value);
                this.ReportPropertyChanging("code");
                this._code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("code");
                this.OncodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _code;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncodeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncodeChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad active en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<short> active
        {
            get
            {
                return this._active;
            }
            set
            {
                this.OnactiveChanging(value);
                this.ReportPropertyChanging("active");
                this._active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("active");
                this.OnactiveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<short> _active;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanging(global::System.Nullable<short> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanged();
        /// <summary>
        /// No hay ningún comentario para States en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PruebaTecnicaNetModel", "FK_Towns_State_Id", "States")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public States States
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<States>("PruebaTecnicaNetModel.FK_Towns_State_Id", "States").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<States>("PruebaTecnicaNetModel.FK_Towns_State_Id", "States").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para States en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<States> StatesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<States>("PruebaTecnicaNetModel.FK_Towns_State_Id", "States");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<States>("PruebaTecnicaNetModel.FK_Towns_State_Id", "States", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para WeatherReports en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PruebaTecnicaNetModel", "FK_WeatherReports_Towns_ID", "WeatherReports")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<WeatherReports> WeatherReports
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<WeatherReports>("PruebaTecnicaNetModel.FK_WeatherReports_Towns_ID", "WeatherReports");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<WeatherReports>("PruebaTecnicaNetModel.FK_WeatherReports_Towns_ID", "WeatherReports", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para PruebaTecnicaNetModel.Users en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// user_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PruebaTecnicaNetModel", Name="Users")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Users : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Users.
        /// </summary>
        /// <param name="user_id">Valor inicial de user_id.</param>
        /// <param name="user_name">Valor inicial de user_name.</param>
        /// <param name="active">Valor inicial de active.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Users CreateUsers(int user_id, string user_name, short active)
        {
            Users users = new Users();
            users.user_id = user_id;
            users.user_name = user_name;
            users.active = active;
            return users;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad user_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this.Onuser_idChanging(value);
                this.ReportPropertyChanging("user_id");
                this._user_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user_id");
                this.Onuser_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _user_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onuser_idChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onuser_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad name en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnameChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad last_name en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string last_name
        {
            get
            {
                return this._last_name;
            }
            set
            {
                this.Onlast_nameChanging(value);
                this.ReportPropertyChanging("last_name");
                this._last_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("last_name");
                this.Onlast_nameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _last_name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onlast_nameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onlast_nameChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad user_name en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string user_name
        {
            get
            {
                return this._user_name;
            }
            set
            {
                this.Onuser_nameChanging(value);
                this.ReportPropertyChanging("user_name");
                this._user_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("user_name");
                this.Onuser_nameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _user_name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onuser_nameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onuser_nameChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad password en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                this.OnpasswordChanging(value);
                this.ReportPropertyChanging("password");
                this._password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("password");
                this.OnpasswordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _password;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpasswordChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpasswordChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad active en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short active
        {
            get
            {
                return this._active;
            }
            set
            {
                this.OnactiveChanging(value);
                this.ReportPropertyChanging("active");
                this._active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("active");
                this.OnactiveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _active;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad last_login_date en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> last_login_date
        {
            get
            {
                return this._last_login_date;
            }
            set
            {
                this.Onlast_login_dateChanging(value);
                this.ReportPropertyChanging("last_login_date");
                this._last_login_date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("last_login_date");
                this.Onlast_login_dateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _last_login_date;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onlast_login_dateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onlast_login_dateChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad token en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string token
        {
            get
            {
                return this._token;
            }
            set
            {
                this.OntokenChanging(value);
                this.ReportPropertyChanging("token");
                this._token = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("token");
                this.OntokenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _token;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntokenChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntokenChanged();
        /// <summary>
        /// No hay ningún comentario para WeatherReports en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PruebaTecnicaNetModel", "FK_WeatherReports_User_Id", "WeatherReports")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<WeatherReports> WeatherReports
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<WeatherReports>("PruebaTecnicaNetModel.FK_WeatherReports_User_Id", "WeatherReports");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<WeatherReports>("PruebaTecnicaNetModel.FK_WeatherReports_User_Id", "WeatherReports", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para PruebaTecnicaNetModel.WeatherReports en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// reports_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PruebaTecnicaNetModel", Name="WeatherReports")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class WeatherReports : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto WeatherReports.
        /// </summary>
        /// <param name="reports_id">Valor inicial de reports_id.</param>
        /// <param name="temperature">Valor inicial de temperature.</param>
        /// <param name="precipitation">Valor inicial de precipitation.</param>
        /// <param name="humidity">Valor inicial de humidity.</param>
        /// <param name="conditions">Valor inicial de conditions.</param>
        /// <param name="report_date">Valor inicial de report_date.</param>
        /// <param name="created_at">Valor inicial de created_at.</param>
        /// <param name="updated_at">Valor inicial de updated_at.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static WeatherReports CreateWeatherReports(int reports_id, string temperature, short precipitation, short humidity, string conditions, global::System.DateTime report_date, global::System.DateTime created_at, global::System.DateTime updated_at)
        {
            WeatherReports weatherReports = new WeatherReports();
            weatherReports.reports_id = reports_id;
            weatherReports.temperature = temperature;
            weatherReports.precipitation = precipitation;
            weatherReports.humidity = humidity;
            weatherReports.conditions = conditions;
            weatherReports.report_date = report_date;
            weatherReports.created_at = created_at;
            weatherReports.updated_at = updated_at;
            return weatherReports;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad reports_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int reports_id
        {
            get
            {
                return this._reports_id;
            }
            set
            {
                this.Onreports_idChanging(value);
                this.ReportPropertyChanging("reports_id");
                this._reports_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("reports_id");
                this.Onreports_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _reports_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onreports_idChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onreports_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad temperature en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string temperature
        {
            get
            {
                return this._temperature;
            }
            set
            {
                this.OntemperatureChanging(value);
                this.ReportPropertyChanging("temperature");
                this._temperature = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("temperature");
                this.OntemperatureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _temperature;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntemperatureChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OntemperatureChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad precipitation en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short precipitation
        {
            get
            {
                return this._precipitation;
            }
            set
            {
                this.OnprecipitationChanging(value);
                this.ReportPropertyChanging("precipitation");
                this._precipitation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("precipitation");
                this.OnprecipitationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _precipitation;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnprecipitationChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnprecipitationChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad humidity en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short humidity
        {
            get
            {
                return this._humidity;
            }
            set
            {
                this.OnhumidityChanging(value);
                this.ReportPropertyChanging("humidity");
                this._humidity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("humidity");
                this.OnhumidityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _humidity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnhumidityChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnhumidityChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad conditions en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string conditions
        {
            get
            {
                return this._conditions;
            }
            set
            {
                this.OnconditionsChanging(value);
                this.ReportPropertyChanging("conditions");
                this._conditions = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("conditions");
                this.OnconditionsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _conditions;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnconditionsChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnconditionsChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad report_date en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime report_date
        {
            get
            {
                return this._report_date;
            }
            set
            {
                this.Onreport_dateChanging(value);
                this.ReportPropertyChanging("report_date");
                this._report_date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("report_date");
                this.Onreport_dateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _report_date;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onreport_dateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onreport_dateChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad created_at en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime created_at
        {
            get
            {
                return this._created_at;
            }
            set
            {
                this.Oncreated_atChanging(value);
                this.ReportPropertyChanging("created_at");
                this._created_at = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("created_at");
                this.Oncreated_atChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _created_at;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncreated_atChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncreated_atChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad updated_at en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime updated_at
        {
            get
            {
                return this._updated_at;
            }
            set
            {
                this.Onupdated_atChanging(value);
                this.ReportPropertyChanging("updated_at");
                this._updated_at = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("updated_at");
                this.Onupdated_atChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _updated_at;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onupdated_atChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onupdated_atChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad active en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<short> active
        {
            get
            {
                return this._active;
            }
            set
            {
                this.OnactiveChanging(value);
                this.ReportPropertyChanging("active");
                this._active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("active");
                this.OnactiveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<short> _active;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanging(global::System.Nullable<short> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnactiveChanged();
        /// <summary>
        /// No hay ningún comentario para Towns en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PruebaTecnicaNetModel", "FK_WeatherReports_Towns_ID", "Towns")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Towns Towns
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Towns>("PruebaTecnicaNetModel.FK_WeatherReports_Towns_ID", "Towns").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Towns>("PruebaTecnicaNetModel.FK_WeatherReports_Towns_ID", "Towns").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Towns en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Towns> TownsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Towns>("PruebaTecnicaNetModel.FK_WeatherReports_Towns_ID", "Towns");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Towns>("PruebaTecnicaNetModel.FK_WeatherReports_Towns_ID", "Towns", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para Users en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PruebaTecnicaNetModel", "FK_WeatherReports_User_Id", "Users")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Users Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("PruebaTecnicaNetModel.FK_WeatherReports_User_Id", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("PruebaTecnicaNetModel.FK_WeatherReports_User_Id", "Users").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Users en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Users> UsersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("PruebaTecnicaNetModel.FK_WeatherReports_User_Id", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Users>("PruebaTecnicaNetModel.FK_WeatherReports_User_Id", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para WeatherEntities en el esquema.
    /// </summary>
    public partial class WeatherEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto WeatherEntities usando la cadena de conexión encontrada en la sección 'WeatherEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public WeatherEntities() : 
                base("name=WeatherEntities", "WeatherEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto WeatherEntities.
        /// </summary>
        public WeatherEntities(string connectionString) : 
                base(connectionString, "WeatherEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto WeatherEntities.
        /// </summary>
        public WeatherEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "WeatherEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para Countries en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Countries> Countries
        {
            get
            {
                if ((this._Countries == null))
                {
                    this._Countries = base.CreateQuery<Countries>("[Countries]");
                }
                return this._Countries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Countries> _Countries;
        /// <summary>
        /// No hay ningún comentario para States en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<States> States
        {
            get
            {
                if ((this._States == null))
                {
                    this._States = base.CreateQuery<States>("[States]");
                }
                return this._States;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<States> _States;
        /// <summary>
        /// No hay ningún comentario para Towns en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Towns> Towns
        {
            get
            {
                if ((this._Towns == null))
                {
                    this._Towns = base.CreateQuery<Towns>("[Towns]");
                }
                return this._Towns;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Towns> _Towns;
        /// <summary>
        /// No hay ningún comentario para Users en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Users> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<Users>("[Users]");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Users> _Users;
        /// <summary>
        /// No hay ningún comentario para WeatherReports en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<WeatherReports> WeatherReports
        {
            get
            {
                if ((this._WeatherReports == null))
                {
                    this._WeatherReports = base.CreateQuery<WeatherReports>("[WeatherReports]");
                }
                return this._WeatherReports;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<WeatherReports> _WeatherReports;
        /// <summary>
        /// No hay ningún comentario para Countries en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCountries(Countries countries)
        {
            base.AddObject("Countries", countries);
        }
        /// <summary>
        /// No hay ningún comentario para States en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToStates(States states)
        {
            base.AddObject("States", states);
        }
        /// <summary>
        /// No hay ningún comentario para Towns en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTowns(Towns towns)
        {
            base.AddObject("Towns", towns);
        }
        /// <summary>
        /// No hay ningún comentario para Users en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
        /// <summary>
        /// No hay ningún comentario para WeatherReports en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToWeatherReports(WeatherReports weatherReports)
        {
            base.AddObject("WeatherReports", weatherReports);
        }
    }
}
